language: ruby
rvm: 2.1.0
script:
   "bundle exec rake"
      #"bundle exec spec"
before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   #- sudo apt-get update -qq
branches:
  only:
    - tests